name: chem-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.12
  - scipy
  - rdkit==2025.09.6
  - ase
  - qcelemental
  - numba
  - pyvista
  - pyvistaqt
  - conda-forge::pyqt
  - scikit-learn==1.9.0
  - openbabel
  - tblite
  - pytest
  - openpyxl
  - conda-forge::plotly
  - conda-forge::python-kaleido
  - conda
  - dscribe
